#!/usr/bin/env bash

version=0.1.0
dir=`dirname $0`

usage() {
  cat <<EOF

  Usage: dots <command>

  Commands:

  i, install              Install dots again
  u, update               Update the homebrew formulae

EOF
  exit
}

while [[ $1 =~ ^- ]]; do
  case $1 in
    -v|--version)
      echo $version
      exit
      ;;
    -h|--help)
      usage
      ;;
  esac
  shift
done

case $1 in
  i|install)
    bash $dir/install
    exit
    ;;
  u|update)
    bash $dir/update
    exit
    ;;
  *) usage
esac
