#!/usr/bin/env bash

#
# Write colored output
#

red() {
  echo -e "\033[0;31m$1\033[0m"
}
cyan() {
  echo -e "\033[0;36m$1\033[0m"
}

#
# Abort with an exit message
#

abort() {
  echo "`red abort:` $1"
  # ring
  echo -en "\007"
  exit 1
}

#
# Ask for sudo access if not already available
# Note: use `sudo -k` to loose sudo access
#

check_sudo() {
  echo "check `cyan sudo`..."
  # without sudo access return nothing
  if [[ -z `sudo -n uptime 2>/dev/null` ]]; then
    # sudo prompt
    sudo echo >/dev/null
  fi
  # one more check if the user abort the password question
  [[ -z `sudo -n uptime 2>/dev/null` ]] && abort 'sudo required'
}

install() {
  echo "install `cyan dots`..."
  local dir=`mktemp -d /tmp/dots.XXXXX`
  cd $dir

  # clone minimal dots (without all repository history)
  [[ -z `type -P git` ]] && abort 'git must be installed'
  git clone --depth 1 https://github.com/jeromedecoster/dots.git
  local lib=/usr/local/lib
  local bin=/usr/local/bin
  mkdir -p $lib
  mkdir -p $bin

  rm -rf $lib/dots
  cd ./dots
  git checkout-index --prefix=$lib/dots/ --all

  # symlink all files from /usr/local/lib/dots/bin to /usr/local/bin
  ls -1 $lib/dots/bin | while read file; do
    rm -f $bin/$file
    ln -s $lib/dots/bin/$file $bin/$file
  done

  # prevent the following error
  # shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
  cd ../..
  rm -rf $dir
  bash $lib/dots/update
}


#
# Run this script
#

check_sudo
install
